version: '3.8'

services:
  dj-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dj-assignment
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash

